project:
  type: website

website:
  title: "My Views"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sijuswamy
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css



